volumes:
  astro_node_modules:

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: nginx
    depends_on:
      - qa-api
      - qa-ui
    ports:
      - "7800:7800"

  qa-api:
    build: qa-api
    image: qa-api
    restart: "no"
    volumes:
      - ./qa-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - flyway
      - redis
      - stream-consumer
    env_file:
      - project.env

  qa-ui:
    build: qa-ui
    image: qa-ui
    restart: "no"
    volumes:
      - ./qa-ui/:/app
      - astro_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - qa-api
      - sse-server

  llm-api:
    build: llm-api
    image: llm-api
    restart: "no"
    expose:
      - 7000
    deploy:
      replicas: 1

  sse-server:
    build: sse-server
    image: sse-server
    restart: "on-failure"
    volumes:
      - ./sse-server/:/app
      - ./app-cache/:/app-cache
    expose:
      - 4000
    env_file:
      - project.env
    depends_on:
      - redis
    deploy:
      replicas: 2
  
  stream-consumer:
    build: stream-consumer
    image: stream-consumer
    restart: "on-failure"
    volumes:
      - ./stream-consumer/:/app
      - ./app-cache/:/app-cache
    expose:
      - 5000
    env_file:
      - project.env
    depends_on:
      - llm-api
      - database
      - redis
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  database:
    container_name: database-server-dab-p2-99f97847-4398-4a1b-b2e5-d211a33c1e01
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests

  redis:
    build: redis
    image: redis
    expose:
      - 6379