version: "3.4"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - qa-api
      - qa-ui
    ports:
      - "7800:7800"

  qa-api:
    build:
      context: qa-api
      dockerfile: Dockerfile.prod
    image: qa-api-prod
    restart: "on-failure"
    expose:
      - 7777
    depends_on:
      - database
      - flyway
      - redis
    env_file:
      - project.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  qa-ui:
    build:
      context: qa-ui
      dockerfile: Dockerfile.prod
    image: qa-ui-prod
    restart: "on-failure"
    expose:
      - 3000
    depends_on:
      - qa-api
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  llm-api:
    build: llm-api
    image: llm-api
    restart: "no"
    expose:
      - 7000
    deploy:
      replicas: 3

  sse-server:
    build:
      context: sse-server
      dockerfile: Dockerfile.prod
    image: sse-server-prod
    restart: "on-failure"
    expose:
      - 4000
    env_file:
      - project.env
    depends_on:
      - qa-api
      - llm-api
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  database:
    container_name: database-server-dab-p2-99f97847-4398-4a1b-b2e5-d211a33c1e01
    image: postgres:14.1
    restart: "unless-stopped"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  redis:
    image: redis:7.4.0
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379