FROM denoland/deno:alpine-2.2.11 AS builder

WORKDIR /app

COPY . .

RUN deno install --entrypoint app.ts


FROM denoland/deno:alpine-2.2.11

WORKDIR /app

COPY --from=builder /app .

CMD [ "task", "start" ]