apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-api-deployment
  labels:
    app: llm-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: llm-api
  template:
    metadata:
      labels:
        app: llm-api
    spec:
      containers:
      - name: llm-api
        image: llm-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: llm-api
spec:
  ports:
  - port: 7000
    targetPort: 7000
  selector:
    app: llm-api