apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-consumer-deployment
spec:
  selector:
    matchLabels:
      app: stream-consumer
  template:
    metadata:
      labels:
        app: stream-consumer
    spec:
      containers:
      - name: stream-consumer
        image: stream-consumer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: PGPASS
          valueFrom:
            secretKeyRef:
              name: qa-api-database-cluster-app
              key: pgpass
              optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: stream-consumer
spec:
  selector:
    app: stream-consumer
  ports:
  - port: 5000
    targetPort: 5000