FROM denoland/deno:alpine-2.2.11 AS builder

EXPOSE 7777

WORKDIR /app

COPY . .

RUN deno install --entrypoint app.js


FROM denoland/deno:alpine-2.2.11

WORKDIR /app

COPY --from=builder /app .

CMD [ "task", "start" ]